version: '3.8'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    volumes:
      - postgres:/var/lib/postgresql/data
  webpack:
    build: .
    command: bash -c "cd bin && ruby webpack-dev-server --inline true"
    volumes:
       - .:/Rails-Docker
    ports:
      - '3035:3035'
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/Rails-Docker
    ports:
      - "3000:3000"
    depends_on:
      - db
      - webpack
volumes:
  postgres: